travis:
  secure:
    BINSTAR_TOKEN: eQKt7sa9kxkC9M+p9m0HW0g9qpTKk+UvKPCGyXPx8mw6EPjsbojRnWeV8p1kd0xh3z9XHAgwQq3GPhIXMva1KfR3xJWAe2LiAEiFmM+6dbKhx5MzOO1OqAnRXidrKrXsP71XzfIlqdkvG/tT/j1Jq1qPJ/x2fpBXxOen8bbU4GyE8vQzExhPv1llVhcK2xcTDHWQHx1ZTeYCdrgbRr14TGBjWm4ezrjh+mpG4rRoY1xiPPnbYkrLvY9iVG3GcGpruQgwEnJcZ11Z4UCI0O+IsoACEpCa8gQXykZUZ9eDaVYSGDjkWU/OuuDr5OvRqw/WgIFCss5rqxzsboH8+kFKig2i1AEk8erz301wthRU6RBAgcpnfM0HVZ4Q8GkBjmGVxqYkZehkhA0fWHRjOQjOysF3pbMzy7E8Ap7ZbIS0GNqlwlBGTRmsSZI22EtyXuGzXgVQa6ku6tor62tl77DAwTu+JKWLMDdNJ/5IOGz7ZiHRb/lNeziu9D524almAQ7SNZty/hKjlkl1MFwvP+HpvwBeQ7Bky7hu8Nh2taTtLAsZJCcpz/rndJEUgm+cmUVIlrGqk4rZgnaK3zTmgrSCZGmSB04sghcA9X8aHrFHavzB/pQ7OlQQSGKDNwN6ku5OL/JXFvLvbaCDRLfYEVEE4TL4Yn1BiFV8iTyg78neDRQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
