travis:
  secure:
    BINSTAR_TOKEN: i356OvJ63ZiRoSDkzB662BQ8/23vkTIgmgO0Mi77PJvOzhZuofKIRepUY+SZEUYl//GM/LJnspxYU+CfIyeiLJ8iDWwMZ5pw77Tv+zhRQ9o5+xc4BBG57PP9DlLBc+3cZMJFYS9Mv4DrlZzgYc07odwuDV33cgLCadtQej1lxPWqpbUf4QjKWHArptwHmTq/8KfhZG0QyojE/oVKEyDiGbzYNwJ/L/BEWCCoCDGeAcYbrAB6NioYZ/kviWhAsni0KTvFk+DIFQEtjPcfdsP0/Mh0LW4IYcIOnTG+cbWoLBG66jSaq1Qea5HgRgsafzj3zEGmSxYIIRIZSz/OZofmLWdhCykLjr0cAHaDRYhHwL+czYHzZInswFY2jaLsDukVA55+UdR2bD5B8DuujolCRPPzbwu/TfzIjyrjl+kcUxBgHTelEjD1WmhHGa2Zs4BIrK3adNGs8koOMa0Z+rht0cFL3gy9P7x6Q5JDJmxt5fX9mXqSaa2FW877Tfm6n/STsG2qdSJksXbEg8dX3dUVNo2vSL6eizCYcaOS8Bs4bNGlp3t7f3MnpzXwqypTX5E19LOxWaIzI64rAbCRV7kUVjzmZ37bkzB0H5l5+xEnbSILQ7bpTjMJr8N2ArEYJDwqIx1GbKQ6ytQ4vIrxqviy3pMiz/DQN73Q4Q3AoE0BeDg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
